from io import BytesIO

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen.canvas import Canvas

from app.models import Payment


def build_payment_receipt(payment: Payment) -> BytesIO:
    stream = BytesIO()
    canvas = Canvas(stream, pagesize=A4)
    width, height = A4
    canvas.setFillColor(HexColor("#07120f"))
    canvas.rect(0, height - 130, width, 130, fill=1, stroke=0)
    canvas.setFillColor(HexColor("#77e6bb"))
    canvas.setFont("Helvetica-Bold", 22)
    canvas.drawString(44, height - 63, "BillFlow AI")
    canvas.setFillColor(HexColor("#ffffff"))
    canvas.setFont("Helvetica", 10)
    canvas.drawString(44, height - 86, "Human-authorized payment receipt")
    canvas.setFillColor(HexColor("#17201d"))
    canvas.setFont("Helvetica-Bold", 18)
    canvas.drawString(44, height - 180, "Payment confirmed")
    rows = [
        ("Receipt", f"BF-{payment.id:07d}"),
        ("Bill", payment.bill.name),
        ("Biller", payment.bill.biller),
        ("Funding source", f"{payment.account.name} {payment.account.masked_identifier}"),
        ("Provider", payment.provider.title()),
        ("Status", payment.status.title()),
        ("Completed", payment.completed_at.isoformat() if payment.completed_at else "Pending"),
    ]
    y = height - 225
    for label, value in rows:
        canvas.setFillColor(HexColor("#718079"))
        canvas.setFont("Helvetica", 9)
        canvas.drawString(44, y, label.upper())
        canvas.setFillColor(HexColor("#17201d"))
        canvas.setFont("Helvetica-Bold", 11)
        canvas.drawString(180, y, str(value))
        y -= 34
    canvas.setFillColor(HexColor("#e2f5ec"))
    canvas.roundRect(44, y - 35, width - 88, 65, 10, fill=1, stroke=0)
    canvas.setFillColor(HexColor("#206c53"))
    canvas.setFont("Helvetica-Bold", 11)
    canvas.drawString(61, y + 5, "AMOUNT PAID")
    canvas.setFont("Helvetica-Bold", 20)
    canvas.drawRightString(width - 61, y, f"INR {float(payment.amount):,.2f}")
    canvas.setFillColor(HexColor("#718079"))
    canvas.setFont("Helvetica", 8)
    canvas.drawString(44, 54, "Generated by BillFlow AI. Provider records remain the source of truth for settlement.")
    canvas.save()
    stream.seek(0)
    return stream

